### ISSUE TITLE
s3-simple can't start new thread when uploading to S3

### ISSUE THREAD

**Issue by uApple** [cloud-gov/s3-resource-simple#53]
When running a put jobs, the resource is failing with `can't start new thread` error

Log is provided below:

```
fetching 18fgsa/s3-resource-simple@sha256:971cf6b8f1628dc9b51883a5de3b0c411ec8bd0f030c4d7d4ba785002af0ac16
677076032cca [========================================] 28.2MiB/28.2MiB
8dc06e55e485 [========================================] 27.6MiB/27.6MiB
dd432980e08f [========================================] 10.0MiB/10.0MiB
87d620264231 [======================================] 110.0MiB/110.0MiB
bc06e923974c [======================================] 829.1KiB/829.1KiB
0cf2e98594a4 [==========================================] 1.7MiB/1.7MiB
de02592f91ad [==========================================] 5.4MiB/5.4MiB
1cf5234db64b [========================================] 31.9MiB/31.9MiB
0e9d17ab554f [==========================================] 1.2KiB/1.2KiB
+ exec
+ exec
+ source=/tmp/build/put
+ [ -z /tmp/build/put ]
+ set +x
+ [ -n  ]
+ cd /tmp/build/put/loopedge-logs
+ echo Uploading to S3...
Uploading to S3...
+ eval aws s3 sync . s3://le-yocto-build-logs/
+ aws s3 sync . s3://le-yocto-build-logs/

can't start new thread
```

Concourse Pipeline resource configuration:
```
resource_types:
- name: s3-simple
  type: registry-image
  source:
    repository: 18fgsa/s3-resource-simple
    username: ((docker-hub-username))
    password: ((docker-hub-password))

- name: loopedge-logs
  type: s3-simple
  source:
    bucket: le-yocto-build-logs
    access_key_id: ((aws_access_key))
    secret_access_key: ((aws_secret))
    change_dir_to: loopedge-logs
```

I would appreciate any assistance with debugging this issue.

## Acceptance Criteria

- [ ] Resource uploads to S3 successfully
